# Run commands in docker container
run: docker run --rm -it --gpus all -v $(pwd):/kaimahi/cose -w /kaimahi/cose -u 1000:1000 docker.dragonfly.co.nz/cose

# Model parameters
data_dir: data
experiment_dir: experiments
eval_dir: eval
experiment_id: $(date +%s)
log_level: INFO

